### ISSUE TITLE
Screen turns blank on evaluation

### ISSUE THREAD

**Issue by Thejus-Paul** [VarunSriram99/Calculator-ReactJS#6]
To replicate the issue,
1. Click `%` operator (It is also applicable for division and multiplication operator).
2. Click on any number.
3. Now click `=` to evaluate.

**Comment by Thejus-Paul** [comment]
This issue can be partially solved by restricting the operators(`*`,`/`,`%`) from being the first input. It also needs to be checked at evaluation since user can also type this expression.

**Comment by VarunSriram99** [comment]
Fixed most of these issues through try catch block.
