### ISSUE TITLE
Cumulative errors on evaluation

### ISSUE THREAD

**Issue by Thejus-Paul** [VarunSriram99/Calculator-ReactJS#9]
To replicate this error, click `Enter`. The error "Operation is Invalid" will pop up. Closing this error message requires only 1 `Enter` key. But if you keep making mistakes, then that error will appear multiple time.

**Comment by VarunSriram99** [comment]
Fixed. Issue with preventing default behaviour of Enter key. No more alerts for irrelevant errors.
